# Generated by Django 2.1.7 on 2019-04-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
